const products = [
  // Cat Food Products (10 items)
  {
    id: 1,
    name: "Premium Cat Salmon Feast",
    price: "899.00",
    originalPrice: "1,199.00",
    discount: 25,
    image: "assets/product/cat_food1.webp",
    category: "cat-food",
    desc: "High-quality salmon-based cat food rich in omega-3 fatty acids for a healthy coat and strong immune system.",
  },
  {
    id: 2,
    name: "Kitten Growth Formula",
    price: "759.00",
    originalPrice: "999.00",
    discount: 24,
    image: "assets/product/cat_food2.webp",
    category: "cat-food",
    desc: "Specially formulated nutrition for growing kittens with essential vitamins and minerals for healthy development.",
  },
  {
    id: 3,
    name: "Indoor Cat Complete Nutrition",
    price: "679.00",
    originalPrice: "899.00",
    discount: 24,
    image: "assets/product/cat_food3.webp",
    category: "cat-food",
    desc: "Balanced diet designed for indoor cats with controlled calories and hairball control formula.",
  },
  {
    id: 4,
    name: "Senior Cat Health Support",
    price: "829.00",
    originalPrice: "1,099.00",
    discount: 25,
    image: "assets/product/cat_food4.webp",
    category: "cat-food",
    desc: "Age-appropriate nutrition for senior cats with joint support and easy-to-digest ingredients.",
  },
  {
    id: 5,
    name: "Grain-Free Cat Chicken",
    price: "949.00",
    originalPrice: "1,249.00",
    discount: 24,
    image: "assets/product/cat_food5.webp",
    category: "cat-food",
    desc: "Grain-free recipe with real chicken as the first ingredient, perfect for cats with sensitive stomachs.",
  },
  {
    id: 6,
    name: "Organic Cat Food Mix",
    price: "1,099.00",
    originalPrice: "1,399.00",
    discount: 21,
    image: "assets/product/cat_food6.webp",
    category: "cat-food",
    desc: "Certified organic cat food made with natural ingredients and no artificial preservatives or colors.",
  },
  {
    id: 7,
    name: "Weight Control Cat Formula",
    price: "799.00",
    originalPrice: "1,049.00",
    discount: 24,
    image: "assets/product/cat_food7.webp",
    category: "cat-food",
    desc: "Low-calorie formula designed to help overweight cats maintain a healthy weight while feeling satisfied.",
  },
  {
    id: 8,
    name: "Hairball Control Cat Food",
    price: "719.00",
    originalPrice: "959.00",
    discount: 25,
    image: "assets/product/cat_food8.webp",
    category: "cat-food",
    desc: "Special fiber blend helps reduce hairballs while providing complete and balanced nutrition.",
  },
  {
    id: 9,
    name: "Cat Tuna & Rice Delight",
    price: "649.00",
    originalPrice: "849.00",
    discount: 24,
    image: "assets/product/cat_food9.webp",
    category: "cat-food",
    desc: "Delicious tuna and rice recipe that cats love, packed with protein and essential nutrients.",
  },
  {
    id: 10,
    name: "Multi-Protein Cat Feast",
    price: "879.00",
    originalPrice: "1,159.00",
    discount: 24,
    image: "assets/product/cat_food10.webp",
    category: "cat-food",
    desc: "A variety of proteins including chicken, fish, and beef to satisfy your cat's taste preferences.",
  },

  // Dog Food Products (10 items)
  {
    id: 11,
    name: "Large Breed Dog Formula",
    price: "1,299.00",
    originalPrice: "1,699.00",
    discount: 24,
    image: "assets/product/dog_food1.webp",
    category: "dog-food",
    desc: "Specially formulated for large breed dogs with glucosamine for joint health and optimal nutrition.",
  },
  {
    id: 12,
    name: "Puppy Growth & Development",
    price: "999.00",
    originalPrice: "1,299.00",
    discount: 23,
    image: "assets/product/dog_food2.webp",
    category: "dog-food",
    desc: "Complete nutrition for growing puppies with DHA for brain development and calcium for strong bones.",
  },
  {
    id: 13,
    name: "Small Breed Adult Dog Food",
    price: "849.00",
    originalPrice: "1,149.00",
    discount: 26,
    image: "assets/product/dog_food3.webp",
    category: "dog-food",
    desc: "Small kibble size perfect for small breed dogs with concentrated nutrition in every bite.",
  },
  {
    id: 14,
    name: "Senior Dog Comfort Food",
    price: "1,199.00",
    originalPrice: "1,599.00",
    discount: 25,
    image: "assets/product/dog_food4.webp",
    category: "dog-food",
    desc: "Gentle nutrition for senior dogs with antioxidants and easy-to-digest ingredients for aging pets.",
  },
  {
    id: 15,
    name: "Active Dog High Energy",
    price: "1,399.00",
    originalPrice: "1,799.00",
    discount: 22,
    image: "assets/product/dog_food5.webp",
    category: "dog-food",
    desc: "High-protein formula designed for active and working dogs to maintain energy and muscle mass.",
  },
  {
    id: 16,
    name: "Sensitive Stomach Dog Food",
    price: "1,149.00",
    originalPrice: "1,499.00",
    discount: 23,
    image: "assets/product/dog_food6.webp",
    category: "dog-food",
    desc: "Gentle formula with limited ingredients for dogs with sensitive stomachs and food allergies.",
  },
  {
    id: 17,
    name: "Grain-Free Dog Chicken",
    price: "1,299.00",
    originalPrice: "1,699.00",
    discount: 24,
    image: "assets/product/dog_food7.webp",
    category: "dog-food",
    desc: "Grain-free recipe with real deboned chicken and sweet potatoes for optimal digestibility.",
  },
  {
    id: 18,
    name: "Weight Management Dog Food",
    price: "1,099.00",
    originalPrice: "1,449.00",
    discount: 24,
    image: "assets/product/dog_food8.webp",
    category: "dog-food",
    desc: "Low-fat formula to help overweight dogs achieve and maintain a healthy weight safely.",
  },
  {
    id: 19,
    name: "Premium Dog Lamb & Rice",
    price: "1,249.00",
    originalPrice: "1,649.00",
    discount: 24,
    image: "assets/product/dog_food9.webp",
    category: "dog-food",
    desc: "High-quality lamb and rice recipe providing excellent protein and easy digestion for all breeds.",
  },
  {
    id: 20,
    name: "Natural Dog Food Blend",
    price: "1,399.00",
    originalPrice: "1,799.00",
    discount: 22,
    image: "assets/product/dog_food10.webp",
    category: "dog-food",
    desc: "Natural ingredients with no artificial colors, flavors, or preservatives for wholesome nutrition.",
  },

  // Cat Toys (15 items)
  {
    id: 21,
    name: "Interactive Feather Wand",
    price: "399.00",
    originalPrice: "529.00",
    discount: 25,
    image: "assets/product/cat_toy1.webp",
    category: "cat-toys",
    desc: "Engaging feather wand toy that stimulates your cat's natural hunting instincts and provides exercise.",
  },
  {
    id: 22,
    name: "Catnip Mouse Set",
    price: "299.00",
    originalPrice: "399.00",
    discount: 25,
    image: "assets/product/cat_toy2.webp",
    category: "cat-toys",
    desc: "Set of realistic mice toys filled with premium catnip to keep your cat entertained for hours.",
  },
  {
    id: 23,
    name: "Puzzle Treat Dispenser",
    price: "699.00",
    originalPrice: "899.00",
    discount: 22,
    image: "assets/product/cat_toy3.webp",
    category: "cat-toys",
    desc: "Mental stimulation toy that dispenses treats as your cat plays, combining fun with reward.",
  },
  {
    id: 24,
    name: "Cat Tunnel Adventure",
    price: "849.00",
    originalPrice: "1,149.00",
    discount: 26,
    image: "assets/product/cat_toy4.webp",
    category: "cat-toys",
    desc: "Collapsible tunnel system perfect for hide-and-seek games and satisfying your cat's curiosity.",
  },
  {
    id: 25,
    name: "Scratching Post Tower",
    price: "1,499.00",
    originalPrice: "1,999.00",
    discount: 25,
    image: "assets/product/cat_toy5.webp",
    category: "cat-toys",
    desc: "Multi-level scratching post with sisal rope and platforms for climbing, scratching, and resting.",
  },
  {
    id: 26,
    name: "Motion Activated Laser",
    price: "799.00",
    originalPrice: "1,049.00",
    discount: 24,
    image: "assets/product/cat_toy6.webp",
    category: "cat-toys",
    desc: "Automatic laser toy that activates when your cat approaches, providing solo entertainment.",
  },
  {
    id: 27,
    name: "Catnip Bubble Maker",
    price: "599.00",
    originalPrice: "799.00",
    discount: 25,
    image: "assets/product/cat_toy7.webp",
    category: "cat-toys",
    desc: "Unique bubble machine that creates catnip-scented bubbles for interactive play and fun.",
  },
  {
    id: 28,
    name: "Cat Exercise Wheel",
    price: "2,499.00",
    originalPrice: "3,299.00",
    discount: 24,
    image: "assets/product/cat_toy8.webp",
    category: "cat-toys",
    desc: "Large exercise wheel designed for cats to run and stay fit, especially great for indoor cats.",
  },
  {
    id: 29,
    name: "Interactive Fish Toy",
    price: "449.00",
    originalPrice: "599.00",
    discount: 25,
    image: "assets/product/cat_toy9.webp",
    category: "cat-toys",
    desc: "Realistic moving fish toy that flops and moves to trigger your cat's predatory instincts.",
  },
  {
    id: 30,
    name: "Cat Teaser Ball Set",
    price: "199.00",
    originalPrice: "259.00",
    discount: 23,
    image: "assets/product/cat_toy10.webp",
    category: "cat-toys",
    desc: "Set of colorful balls with different textures and sounds to keep your cat engaged and active.",
  },
  {
    id: 31,
    name: "Multi-Level Cat Tree",
    price: "1,899.00",
    originalPrice: "2,499.00",
    discount: 24,
    image: "assets/product/cat_toy11.webp",
    category: "cat-toys",
    desc: "Spacious cat tree with multiple platforms, scratching posts, and cozy hideaways for ultimate comfort.",
  },
  {
    id: 32,
    name: "Smart Motion Ball",
    price: "699.00",
    originalPrice: "929.00",
    discount: 25,
    image: "assets/product/cat_toy12.webp",
    category: "cat-toys",
    desc: "Self-rolling ball that changes direction automatically, keeping your cat chasing and playing.",
  },
  {
    id: 33,
    name: "Catnip Garden Kit",
    price: "359.00",
    originalPrice: "479.00",
    discount: 25,
    image: "assets/product/cat_toy13.webp",
    category: "cat-toys",
    desc: "Grow your own fresh catnip with this complete kit including seeds, soil, and growing instructions.",
  },
  {
    id: 34,
    name: "Window Bird Feeder Toy",
    price: "899.00",
    originalPrice: "1,199.00",
    discount: 25,
    image: "assets/product/cat_toy14.webp",
    category: "cat-toys",
    desc: "Window-mounted bird feeder that attracts birds for your cat's viewing pleasure and entertainment.",
  },
  {
    id: 35,
    name: "Cat Activity Center",
    price: "1,299.00",
    originalPrice: "1,699.00",
    discount: 24,
    image: "assets/product/cat_toy15.webp",
    category: "cat-toys",
    desc: "Complete activity center with scratching surfaces, toys, and resting areas in one compact unit.",
  },

  // Dog Toys (15 items)
  {
    id: 36,
    name: "Rope Tug Toy",
    price: "299.00",
    originalPrice: "399.00",
    discount: 25,
    image: "assets/product/dog_toy1.webp",
    category: "dog-toys",
    desc: "Durable rope toy perfect for tug-of-war games and helping to clean your dog's teeth while playing.",
  },
  {
    id: 37,
    name: "Squeaky Duck Toy",
    price: "249.00",
    originalPrice: "329.00",
    discount: 24,
    image: "assets/product/dog_toy2.webp",
    category: "dog-toys",
    desc: "Classic squeaky duck toy that provides auditory stimulation and hours of playful entertainment.",
  },
  {
    id: 38,
    name: "Tennis Ball Set",
    price: "199.00",
    originalPrice: "259.00",
    discount: 23,
    image: "assets/product/dog_toy3.webp",
    category: "dog-toys",
    desc: "Set of high-quality tennis balls perfect for fetch games and outdoor activities with your dog.",
  },
  {
    id: 39,
    name: "Puzzle Treat Toy",
    price: "599.00",
    originalPrice: "799.00",
    discount: 25,
    image: "assets/product/dog_toy4.webp",
    category: "dog-toys",
    desc: "Interactive puzzle toy that challenges your dog's mind while rewarding them with hidden treats.",
  },
  {
    id: 40,
    name: "Chew Bone Large",
    price: "449.00",
    originalPrice: "599.00",
    discount: 25,
    image: "assets/product/dog_toy5.webp",
    category: "dog-toys",
    desc: "Long-lasting chew bone made from safe materials to satisfy your dog's natural chewing instinct.",
  },
  {
    id: 41,
    name: "Frisbee Flying Disc",
    price: "359.00",
    originalPrice: "479.00",
    discount: 25,
    image: "assets/product/dog_toy6.webp",
    category: "dog-toys",
    desc: "Soft, flexible frisbee designed for safe catching and throwing games in the yard or park.",
  },
  {
    id: 42,
    name: "Interactive Ball Launcher",
    price: "1,499.00",
    originalPrice: "1,999.00",
    discount: 25,
    image: "assets/product/dog_toy7.webp",
    category: "dog-toys",
    desc: "Automatic ball launcher that provides endless fetch games, perfect for high-energy dogs.",
  },
  {
    id: 43,
    name: "Plush Comfort Toy",
    price: "399.00",
    originalPrice: "529.00",
    discount: 25,
    image: "assets/product/dog_toy8.webp",
    category: "dog-toys",
    desc: "Soft, cuddly plush toy that provides comfort and companionship, especially for anxious dogs.",
  },
  {
    id: 44,
    name: "Rubber Kong Classic",
    price: "299.00",
    originalPrice: "399.00",
    discount: 25,
    image: "assets/product/dog_toy9.webp",
    category: "dog-toys",
    desc: "Durable rubber toy that can be stuffed with treats, providing mental stimulation and long-lasting fun.",
  },
  {
    id: 45,
    name: "Agility Training Set",
    price: "1,299.00",
    originalPrice: "1,699.00",
    discount: 24,
    image: "assets/product/dog_toy10.webp",
    category: "dog-toys",
    desc: "Complete agility training kit with hurdles, tunnels, and poles for active training and exercise.",
  },
  {
    id: 46,
    name: "Snuffle Mat Foraging",
    price: "699.00",
    originalPrice: "929.00",
    discount: 25,
    image: "assets/product/dog_toy11.webp",
    category: "dog-toys",
    desc: "Foraging mat that encourages natural sniffing behavior and slows down eating for better digestion.",
  },
  {
    id: 47,
    name: "Tug & Fetch Combo",
    price: "449.00",
    originalPrice: "599.00",
    discount: 25,
    image: "assets/product/dog_toy12.webp",
    category: "dog-toys",
    desc: "Versatile toy combining tug-of-war and fetch capabilities in one durable, fun package.",
  },
  {
    id: 48,
    name: "Treat Dispensing Ball",
    price: "399.00",
    originalPrice: "529.00",
    discount: 25,
    image: "assets/product/dog_toy13.webp",
    category: "dog-toys",
    desc: "Rolling ball that dispenses treats as your dog plays, encouraging active play and mental stimulation.",
  },
  {
    id: 49,
    name: "Cooling Chew Toy",
    price: "549.00",
    originalPrice: "729.00",
    discount: 25,
    image: "assets/product/dog_toy14.webp",
    category: "dog-toys",
    desc: "Cooling chew toy that can be frozen to soothe teething puppies or provide relief on hot days.",
  },
  {
    id: 50,
    name: "Multi-Texture Play Set",
    price: "799.00",
    originalPrice: "1,059.00",
    discount: 25,
    image: "assets/product/dog_toy15.webp",
    category: "dog-toys",
    desc: "Set of toys with different textures and functions to keep your dog engaged and entertained.",
  },

  // Walk Gear (16 items)
  {
    id: 51,
    name: "Adjustable Dog Harness",
    price: "899.00",
    originalPrice: "1,199.00",
    discount: 25,
    image: "assets/product/walk_gear1.webp",
    category: "walk-gear",
    desc: "Comfortable, adjustable harness with padded chest plate for secure and comfortable dog walks.",
  },
  {
    id: 52,
    name: "Retractable Dog Leash",
    price: "699.00",
    originalPrice: "929.00",
    discount: 25,
    image: "assets/product/walk_gear2.webp",
    category: "walk-gear",
    desc: "Durable retractable leash with smooth extending mechanism and comfortable grip handle.",
  },
  {
    id: 53,
    name: "LED Safety Collar",
    price: "599.00",
    originalPrice: "799.00",
    discount: 25,
    image: "assets/product/walk_gear3.webp",
    category: "walk-gear",
    desc: "Bright LED collar for nighttime visibility and safety during evening walks and outdoor activities.",
  },
  {
    id: 54,
    name: "Dog Walking Belt",
    price: "549.00",
    originalPrice: "729.00",
    discount: 25,
    image: "assets/product/walk_gear4.webp",
    category: "walk-gear",
    desc: "Hands-free walking belt with bungee leash attachment for comfortable jogging and hiking with your dog.",
  },
  {
    id: 55,
    name: "Poop Bag Dispenser",
    price: "199.00",
    originalPrice: "259.00",
    discount: 23,
    image: "assets/product/walk_gear5.webp",
    category: "walk-gear",
    desc: "Convenient poop bag dispenser that attaches to any leash, complete with biodegradable bags.",
  },
  {
    id: 56,
    name: "Dog Booties Set",
    price: "799.00",
    originalPrice: "1,059.00",
    discount: 25,
    image: "assets/product/walk_gear6.webp",
    category: "walk-gear",
    desc: "Protective booties to shield your dog's paws from hot pavement, snow, and rough terrain.",
  },
  {
    id: 57,
    name: "Reflective Dog Vest",
    price: "649.00",
    originalPrice: "859.00",
    discount: 24,
    image: "assets/product/walk_gear7.webp",
    category: "walk-gear",
    desc: "High-visibility reflective vest to keep your dog safe and visible during low-light conditions.",
  },
  {
    id: 58,
    name: "Portable Water Bottle",
    price: "449.00",
    originalPrice: "599.00",
    discount: 25,
    image: "assets/product/walk_gear8.webp",
    category: "walk-gear",
    desc: "Convenient water bottle with attached bowl for keeping your dog hydrated during walks and hikes.",
  },
  {
    id: 59,
    name: "Training Treat Pouch",
    price: "299.00",
    originalPrice: "399.00",
    discount: 25,
    image: "assets/product/walk_gear9.webp",
    category: "walk-gear",
    desc: "Clip-on treat pouch with easy-access opening for reward-based training during walks.",
  },
  {
    id: 60,
    name: "No-Pull Harness System",
    price: "1,199.00",
    originalPrice: "1,599.00",
    discount: 25,
    image: "assets/product/walk_gear10.webp",
    category: "walk-gear",
    desc: "Specialized harness designed to reduce pulling behavior while maintaining comfort for your dog.",
  },
  {
    id: 61,
    name: "Dog Backpack Carrier",
    price: "1,499.00",
    originalPrice: "1,999.00",
    discount: 25,
    image: "assets/product/walk_gear11.webp",
    category: "walk-gear",
    desc: "Comfortable backpack carrier for small dogs, perfect for longer hikes and crowded areas.",
  },
  {
    id: 62,
    name: "Hands-Free Leash System",
    price: "899.00",
    originalPrice: "1,199.00",
    discount: 25,
    image: "assets/product/walk_gear12.webp",
    category: "walk-gear",
    desc: "Complete hands-free walking system with waist belt and bungee leash for active pet parents.",
  },
  {
    id: 63,
    name: "Dog ID Tag Set",
    price: "249.00",
    originalPrice: "329.00",
    discount: 24,
    image: "assets/product/walk_gear13.webp",
    category: "walk-gear",
    desc: "Durable ID tags with customizable engraving to keep your pet's information safe and accessible.",
  },
  {
    id: 64,
    name: "Multi-Dog Leash Coupler",
    price: "399.00",
    originalPrice: "529.00",
    discount: 25,
    image: "assets/product/walk_gear14.webp",
    category: "walk-gear",
    desc: "Tangle-free coupler system for walking multiple dogs safely and comfortably at the same time.",
  },
  {
    id: 65,
    name: "Dog GPS Collar Tracker",
    price: "2,499.00",
    originalPrice: "3,299.00",
    discount: 24,
    image: "assets/product/walk_gear15.webp",
    category: "walk-gear",
    desc: "Advanced GPS tracking collar to monitor your dog's location and activity levels in real-time.",
  },
  {
    id: 66,
    name: "Professional Grooming Kit",
    price: "1,299.00",
    originalPrice: "1,699.00",
    discount: 24,
    image: "assets/product/walk_gear16.webp",
    category: "walk-gear",
    desc: "Complete grooming kit with brushes, nail clippers, and accessories for maintaining your pet's hygiene.",
  }
];